const { _electron: electron, expect } = require('@playwright/test');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { Store } = require('../src/core.cjs');
(async () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'piku-ui-'));
  const env = { ...process.env, PIKU_TEST_USER_DATA: directory };
  delete env.ELECTRON_RUN_AS_NODE;
  const store = new Store(directory);
  const task = store.add({ title: '整理下周项目汇报', notes: '汇总本周进度与下一步计划', priority: 'high', category: 'work' });
  store.add({ title: '下班后取快递', priority: 'medium', category: 'life' });
  store.add({ title: '读完正在看的那本书', priority: 'low', category: 'growth' });
  let instance;
  try {
    instance = await electron.launch({ args: ['.'], cwd: path.join(__dirname, '..'), env });
    await expect.poll(() => instance.windows().some(w => w.url().endsWith('/ui/index.html'))).toBe(true);
    const window = instance.windows().find(w => w.url().endsWith('/ui/index.html')); const errors = [];
    await expect.poll(() => instance.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/ui/index.html')).isVisible())).toBe(true);
    window.on('pageerror', error => errors.push(error.message));
    await expect(window.locator('h1')).toContainText('待办清单');
    await expect(window.locator('.task-row')).toHaveCount(3);
    await window.screenshot({ path: path.join(__dirname, '../test-output/main-list.png') });
    await window.getByRole('button', { name: '整理下周项目汇报', exact: true }).click();
    await expect(window.locator('.detail-notes')).toContainText('汇总本周进度与下一步计划');
    await expect(window.locator('#modal input')).toHaveCount(0);
    await window.screenshot({ path: path.join(__dirname, '../test-output/task-detail.png') });
    await window.getByRole('button', { name: '关闭', exact: true }).click();
    await window.getByRole('button', { name: '文字记录', exact: true }).click();
    await expect(window.locator('#task-form input:visible')).toHaveCount(1);
    await expect(window.locator('#task-form select, #task-form [name="reminderAt"]')).toHaveCount(0);
    await window.locator('#title').fill('测试：预约理发');
    fs.mkdirSync(path.join(__dirname, '../test-output'), { recursive: true });
    await window.screenshot({ path: path.join(__dirname, '../test-output/quick-add.png') });
    await window.locator('#title').press('Enter');
    await expect(window.getByRole('button', { name: '测试：预约理发', exact: true })).toBeVisible();
    const savedTask = () => JSON.parse(fs.readFileSync(path.join(directory, 'state.json'), 'utf8')).tasks.find(t => t.title === '测试：预约理发');
    if (savedTask().dueAt !== null || savedTask().reminderAt !== null) throw new Error('A plain task must not acquire dates or reminders');
    await window.getByRole('button', { name: '测试：预约理发', exact: true }).click();
    await expect(window.locator('#task-form')).toHaveCount(0);
    await window.getByRole('button', { name: '编辑', exact: true }).click();
    await window.locator('.deadline-field summary').click();
    await window.getByLabel('截止时间', { exact: true }).fill('2099-12-31T15:30');
    await window.getByRole('button', { name: '保存修改', exact: true }).click();
    await expect(window.locator('#modal')).not.toBeVisible();
    if (savedTask().dueAt !== new Date('2099-12-31T15:30').toISOString() || savedTask().reminderAt !== null) throw new Error('Deadline should be stored without scheduling a reminder');
    await window.getByRole('button', { name: '测试：预约理发', exact: true }).click();
    await expect(window.locator('#task-form')).toHaveCount(0);
    await window.getByRole('button', { name: '编辑', exact: true }).click();
    await window.getByRole('button', { name: '清除', exact: true }).click();
    await window.getByRole('button', { name: '保存修改', exact: true }).click();
    await expect(window.locator('#modal')).not.toBeVisible();
    if (savedTask().dueAt !== null) throw new Error('Deadline was not cleared');
    await window.getByRole('button', { name: '测试：预约理发', exact: true }).click();
    await window.getByRole('button', { name: '标记完成', exact: true }).click();
    await expect(window.locator('#modal')).not.toBeVisible();
    await expect(window.getByRole('button', { name: '测试：预约理发', exact: true })).toHaveCount(0);
    await window.locator('[data-page="settings"]').click();
    await expect(window.getByRole('button', { name: '使用 ChatGPT 登录 ↗' })).toBeVisible();
    await expect(window.locator('input[type="password"]')).toHaveCount(0);
    await window.getByRole('button', { name: '刷新连接' }).click();
    await instance.evaluate(({ shell }, taskId) => {
      const { CodexClient } = process.getBuiltinModule('module').createRequire(process.cwd() + '/package.json')('./src/codex.cjs');
      let account = null;
      shell.openExternal = async url => { global.__loginUrl = url; };
      global.__finishLogin = () => { account = { type: 'chatgpt', email: 'test@example.com', planType: 'plus' }; global.__client.emit('notification', 'account/login/completed', { loginId: 'ui-login', success: true }); };
      CodexClient.prototype.request = async function(method, params) {
        global.__client = this;
        if (method === 'account/read') return { account };
        if (method === 'model/list') return { data: [{ model: 'test-model', displayName: 'Test model', isDefault: true }] };
        if (method === 'account/login/start') return { loginId: 'ui-login', authUrl: 'https://auth.openai.com/authorize?state=test' };
        if (method === 'account/logout') { account = null; return {}; }
        if (method === 'thread/start') return { thread: { id: 'test-thread' } };
        if (method === 'turn/start') {
          const judged = params.outputSchema.properties.decision ? JSON.parse(params.input[0].text.split('待办：').at(-1)) : null;
          if (judged) (global.__judgedIds ||= []).push(judged.id);
          const result = judged ? (judged.title.includes('写一份测试通知') ? { decision: 'agent', reason: '可以根据给定内容生成完整文稿。', humanStep: '', actions: [{ taskId: judged.id, kind: 'draft', title: '保存测试通知', reason: '准备完整文稿', content: '通知：明天上午九点开会。', url: null, reminderAt: null }] } : { decision: 'human', reason: '需要本人实际处理。', humanStep: '按事项要求完成。', actions: [] }) : params.outputSchema.properties.summary
            ? { summary: '先完成项目汇报，再把生活中的小事逐一安排好。', focus: [{ taskId, reason: '提前准备更从容', nextStep: '先列出本周完成的三个重点', priority: 'high' }], actions: [{ taskId, kind: 'draft', title: '为项目汇报准备一份提纲', reason: '先把结构搭好，你可以在此基础上补充具体进度。', content: '本周进度：已完成事项、进行中的事项。下周计划：重点工作。', url: null, reminderAt: null }] }
            : { tasks: [{ title: '测试：购买洗衣液', notes: '粘贴消息提取', dueAt: null, reminderAt: null, priority: 'low', category: 'life' }] };
          setTimeout(() => this.emit('notification', 'turn/completed', { threadId: 'test-thread', turn: { id: 'test-turn', status: 'completed', items: [{ type: 'agentMessage', text: JSON.stringify(result) }] } }), 10);
          return { turn: { id: 'test-turn' } };
        }
        return {};
      };
    }, task.id);
    await window.getByRole('button', { name: '使用 ChatGPT 登录 ↗' }).click();
    await expect(window.getByRole('button', { name: '取消登录' })).toBeVisible();
    await window.getByRole('button', { name: '取消登录' }).click();
    await expect(window.getByRole('button', { name: '使用 ChatGPT 登录 ↗' })).toBeVisible();
    await window.getByRole('button', { name: '使用 ChatGPT 登录 ↗' }).click();
    await instance.evaluate(() => global.__finishLogin());
    await expect(window.locator('.account-box')).toContainText('test@example.com');
    await expect(window.locator('#model option')).toHaveCount(2);
    await window.locator('.more-menu summary').click();
    await window.locator('[data-page="actions"]').click();
    await window.getByRole('button', { name: /分析我的待办/ }).click();
    await expect(window.getByRole('heading', { name: '为项目汇报准备一份提纲' })).toBeVisible();
    fs.mkdirSync(path.join(__dirname, '../test-output'), { recursive: true });
    await window.screenshot({ path: path.join(__dirname, '../test-output/desktop.png') });
    await window.getByRole('button', { name: '查看并授权 →' }).click();
    await expect(window.locator('.draft-preview')).toContainText('本周进度');
    await window.getByRole('button', { name: '授权并执行' }).click();
    await expect(window.getByRole('button', { name: '在 Finder 中查看文稿' })).toBeVisible();
    const files = fs.readdirSync(path.join(directory, 'drafts'));
    if (files.length !== 1) throw new Error('Draft was not created exactly once');
    await window.getByRole('button', { name: '关闭', exact: true }).click();
    await window.locator('.more-menu summary').click();
    await window.getByRole('button', { name: '粘贴消息 ↗' }).click();
    await window.locator('textarea').fill('记得购买洗衣液');
    await window.getByRole('button', { name: /提取待办/ }).click();
    await expect(window.locator('#import-form')).toContainText('测试：购买洗衣液');
    await window.getByRole('button', { name: '加入清单' }).click();
    await window.locator('[data-page="tasks"]').first().click();
    await expect(window.getByRole('button', { name: '测试：购买洗衣液', exact: true })).toBeVisible();
    await window.locator('#search').fill('洗衣液');
    await expect(window.locator('.task-row')).toHaveCount(1);
    await window.getByRole('button', { name: '测试：购买洗衣液', exact: true }).click();
    await window.getByRole('button', { name: '编辑', exact: true }).click();
    await window.getByRole('button', { name: '删除待办', exact: true }).click();
    await window.getByRole('button', { name: '确认删除', exact: true }).click();
    await expect(window.locator('.task-row')).toHaveCount(0);
    // Exercise capture UI with a controlled fixture; never capture the user's desktop.
    const fixture = path.join(directory, 'fixture.png');
    await window.screenshot({ path: fixture });
    await instance.evaluate(({ systemPreferences }, fixture) => {
      systemPreferences.getMediaAccessStatus = () => 'granted';
      const { RegionCapture } = process.getBuiltinModule('module').createRequire(process.cwd() + '/package.json')('./src/capture.cjs');
      RegionCapture.prototype.take = async () => ({ file: fixture, cleanup: () => { global.__captureCleaned = (global.__captureCleaned || 0) + 1; } });
    }, fixture);
    const countTasks = () => JSON.parse(fs.readFileSync(path.join(directory, 'state.json'), 'utf8')).tasks.length;
    let initialCount = countTasks();
    const floating = instance.windows().find(page => page.url().endsWith('/ui/floating.html'));
    await expect(floating.locator('button')).toBeVisible();
    const quickEvent = instance.waitForEvent('window');
    await floating.locator('button').click();
    const quick = await quickEvent;
    quick.on('pageerror', error => errors.push(error.message));
    await expect(quick.locator('button')).toHaveCount(1);
    await expect(quick.locator('input')).toHaveCount(1);
    await quick.getByLabel('记下一件事').fill('快速输入：取快递');
    await quick.getByLabel('记下一件事').press('Enter');
    await expect.poll(countTasks).toBe(initialCount + 1);
    await expect(quick.getByLabel('记下一件事')).toHaveValue('');
    initialCount = countTasks();
    await quick.getByLabel('记下一件事').fill('还没写完');
    await quick.keyboard.press('Escape');
    await floating.locator('button').click();
    await expect(quick.getByLabel('记下一件事')).toHaveValue('还没写完');
    await quick.screenshot({ path: path.join(__dirname, '../test-output/quick-capture.png') });
    const previewEvent = instance.waitForEvent('window');
    await quick.getByRole('button', { name: '框选截图' }).click();
    const preview = await previewEvent;
    preview.on('pageerror', error => errors.push(error.message));
    await expect(preview.getByLabel('事项 1', { exact: true })).toHaveValue('测试：购买洗衣液');
    if (countTasks() !== initialCount) throw new Error('Capture saved without confirmation');
    await preview.getByLabel('事项 1', { exact: true }).fill('截图确认：购买洗衣液');
    await expect(preview.locator('.task')).toHaveCount(1);
    await preview.locator('.capture-notes summary').click();
    await preview.getByLabel('具体内容 1', { exact: true }).fill('买洗衣液\n顺路取快递');
    await preview.screenshot({ path: path.join(__dirname, '../test-output/capture-review.png') });
    await preview.locator('[type=submit]').click();
    await expect.poll(countTasks).toBe(initialCount + 1);
    const capturedTask = JSON.parse(fs.readFileSync(path.join(directory, 'state.json'), 'utf8')).tasks.find(t => t.title === '截图确认：购买洗衣液');
    if (!capturedTask || capturedTask.reminderAt !== null) throw new Error('Capture edit or reminder policy failed');
    if (capturedTask.notes !== '买洗衣液\n顺路取快递') throw new Error('Screenshot details were not preserved in one task');
    await instance.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/ui/index.html')).show());
    const cancelEvent = instance.waitForEvent('window');
    await window.getByRole('button', { name: '截图记事', exact: true }).click();
    const cancelPreview = await cancelEvent;
    await expect(cancelPreview.getByLabel('事项 1', { exact: true })).toBeVisible();
    await cancelPreview.keyboard.press('Escape').catch(error => { if (!cancelPreview.isClosed()) throw error; });
    await expect.poll(() => instance.evaluate(() => global.__captureCleaned)).toBe(2);
    if (countTasks() !== initialCount + 1) throw new Error('Cancelled capture saved a task');
    await instance.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/ui/index.html')).show());
    await window.locator('[data-page="tasks"]').first().click();
    await window.getByRole('button', { name: '文字记录', exact: true }).click();
    await window.locator('#title').fill('写一份测试通知：明天上午九点开会');
    await window.locator('#title').press('Enter');
    await window.getByRole('button', { name: '写一份测试通知：明天上午九点开会', exact: true }).click();
    await expect(window.getByRole('button', { name: '判断助手能否执行', exact: true })).toBeVisible();
    await expect(window.locator('.judgment-panel')).not.toContainText('正在判断');
    if (await instance.evaluate(() => (global.__judgedIds || []).length) !== 0) throw new Error('Judgment started before a manual click');
    await window.getByRole('button', { name: '判断助手能否执行', exact: true }).click();
    await expect(window.locator('.judgment-panel')).toContainText('助手可完成', { timeout: 15000 });
    if (await instance.evaluate(() => global.__judgedIds.length) !== 1) throw new Error('Manual click judged more than one task');
    if (fs.readdirSync(path.join(directory, 'drafts')).length !== 1) throw new Error('Judgment executed without consent');
    await window.screenshot({ path: path.join(__dirname, '../test-output/task-judgment.png') });
    await window.getByRole('button', { name: '查看并确认', exact: true }).click();
    await expect(window.locator('.draft-preview')).toContainText('明天上午九点开会');
    await window.getByRole('button', { name: '授权并执行', exact: true }).click();
    await expect(window.getByRole('button', { name: '在 Finder 中查看文稿' })).toBeVisible();
    if (fs.readdirSync(path.join(directory, 'drafts')).length !== 2) throw new Error('Approved judgment did not execute once');
    await window.getByRole('button', { name: '关闭', exact: true }).click();
    if (errors.length) throw new Error(errors.join('\n'));
    await window.locator('[data-page="settings"]').click();
    await window.getByRole('button', { name: '退出登录', exact: true }).click();
    await expect(window.getByRole('button', { name: '使用 ChatGPT 登录 ↗' })).toBeVisible();
    await window.screenshot({ path: path.join(__dirname, '../test-output/chatgpt-login.png') });
    console.log('PASS: ChatGPT login, cancel, account/model refresh, logout, mock analysis/extract, task CRUD, approval and draft execution; no renderer errors.');
  } finally {
    if (instance) await instance.evaluate(({ app }) => app.quit()).catch(() => {});
    if (instance) await instance.close().catch(() => {});
    fs.rmSync(directory, { recursive: true, force: true });
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
